import React from 'react';
import type { OpportunityResult } from '../services/targets.service';

export const OpportunityMapView: React.FC<{ result: OpportunityResult | null; loading: boolean }> = ({ result, loading }) => {
  if (loading) return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Loading offering matches…</p></section>;
  if (!result?.set) return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-slate-900">Offering matches</h2><p className="mt-1 text-sm text-slate-500">Run research, then match approved offerings to evidence.</p></section>;
  if (!result.opportunities.length) return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-slate-900">Offering matches</h2><p className="mt-2 text-sm text-slate-600">{result.set.resultReason || 'No evidence-backed offering match yet.'}</p></section>;
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-slate-900">Evidence-backed offering matches</h2><p className="mt-1 text-xs text-slate-500">Sales Potential is a priority rubric, not buying probability. Coverage shows how much of the rubric has supporting information.</p><div className="mt-4 space-y-4">{result.opportunities.map(item => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-bold text-slate-900">{item.offeringName}</h3><p className="mt-1 text-sm text-slate-700">{item.targetNeed}</p></div><div className="text-right text-sm"><strong className="text-teal-700">{item.score}/100</strong><span className="block text-xs text-slate-500">{item.coverage}% evidence coverage · {item.evidenceConfidence}</span></div></div><p className="mt-3 text-sm text-slate-600">{item.rationale}</p><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="font-bold text-slate-700">Why now</dt><dd>{item.whyNow}</dd></div><div><dt className="font-bold text-slate-700">Entry action</dt><dd>{item.entryAction}</dd></div></dl><p className="mt-3 text-xs text-slate-500">{item.needKind === 'confirmed_need' ? 'Supported need' : 'Discovery hypothesis'} · Evidence: {item.evidence.map(e => e.statement).join(' · ')}</p>{item.uncertainties.length > 0 && <p className="mt-2 text-xs text-amber-700">Assumptions: {item.uncertainties.join(' ')}</p>}<details className="mt-3 text-xs text-slate-600"><summary className="cursor-pointer font-bold text-teal-700">Score details</summary><ul className="mt-2 space-y-1">{Object.entries(item.scoreBreakdown).map(([name, value]) => <li key={name}>{name}: {value.value === null ? 'Unavailable' : `${value.value}/100`} ({value.weight}% weight) — {value.reason}</li>)}</ul></details></article>)}</div></section>;
};
