import React, { useMemo, useState } from 'react';
import type { ResearchEvidence, TargetIntelligence } from '../services/targets.service';

type Tab = 'overview' | 'technology' | 'stakeholders' | 'signals' | 'gaps' | 'sources';
const tabs: Array<[Tab, string]> = [['overview', 'Overview'], ['technology', 'Tech DNA'], ['stakeholders', 'Stakeholders'], ['signals', 'Buying signals'], ['gaps', 'Potential gaps'], ['sources', 'Sources']];

const badge = (value: string) => <span className={`rounded-full px-2 py-1 text-[11px] font-bold ${value === 'confirmed' || value === 'high' ? 'bg-teal-50 text-teal-800' : value === 'likely' || value === 'medium' ? 'bg-amber-50 text-amber-800' : 'bg-slate-100 text-slate-600'}`}>{value.replace(/_/g, ' ')}</span>;

export const TargetIntelligenceView: React.FC<{ intelligence: TargetIntelligence | null; evidence: ResearchEvidence | null; loading?: boolean }> = ({ intelligence, evidence, loading }) => {
  const [tab, setTab] = useState<Tab>('overview');
  const claimById = useMemo(() => new Map((evidence?.claims || []).map(claim => [claim.id, claim])), [evidence]);
  if (loading) return <p role="status" className="text-sm text-slate-500">Loading account intelligence…</p>;
  if (!intelligence?.run) return <div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">No completed evidence-backed research yet. Run research to build account intelligence.</div>;
  const stale = !!intelligence.run.endedAt && Date.now() - new Date(intelligence.run.endedAt).getTime() > 30 * 24 * 60 * 60 * 1000;
  const evidenceFor = (claimId: string) => {
    const claim = claimById.get(claimId);
    return claim ? <p className="mt-2 text-xs text-slate-500">Evidence: {claim.statement}</p> : <p className="mt-2 text-xs text-slate-500">Evidence unavailable in this view.</p>;
  };
  const empty = (text: string) => <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">{text}</p>;
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">Account intelligence</h2><p className="mt-1 text-sm text-slate-500">Derived from source-linked research. Hypotheses need validation in discovery.</p></div>{stale && <span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-800">Research older than 30 days</span>}</div>
    <div className="mt-4 flex flex-wrap gap-2" role="tablist">{tabs.map(([id, label]) => <button key={id} role="tab" aria-selected={tab === id} onClick={() => setTab(id)} className={`rounded-lg px-3 py-2 text-xs font-bold ${tab === id ? 'bg-teal-600 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>{label}</button>)}</div>
    <div className="mt-5">
      {tab === 'overview' && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl bg-slate-50 p-4"><strong className="text-2xl">{intelligence.technologies.length}</strong><p className="text-xs text-slate-500">Technologies</p></div><div className="rounded-xl bg-slate-50 p-4"><strong className="text-2xl">{intelligence.people.length}</strong><p className="text-xs text-slate-500">Sourced stakeholders</p></div><div className="rounded-xl bg-slate-50 p-4"><strong className="text-2xl">{intelligence.signals.length}</strong><p className="text-xs text-slate-500">Buying signals</p></div><div className="rounded-xl bg-slate-50 p-4"><strong className="text-2xl">{intelligence.gaps.length}</strong><p className="text-xs text-slate-500">Gap hypotheses</p></div><p className="sm:col-span-2 lg:col-span-4 text-xs text-slate-500">Completed {intelligence.run.endedAt ? new Date(intelligence.run.endedAt).toLocaleString() : 'date unknown'} · Unknown data stays unknown.</p></div>}
      {tab === 'technology' && (intelligence.technologies.length ? <div className="space-y-3">{intelligence.technologies.map(item => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center gap-2"><strong>{item.name}</strong>{badge(item.status)}<span className="text-xs text-slate-500">{item.category}</span></div><p className="mt-2 text-sm text-slate-600">{item.rationale}</p>{item.observedAt && <p className="mt-1 text-xs text-slate-500">Observed: {item.observedAt}</p>}{evidenceFor(item.claimId)}</article>)}</div> : empty('No technology findings with sufficient evidence.'))}
      {tab === 'stakeholders' && (intelligence.people.length ? <div className="space-y-3">{intelligence.people.map(item => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center gap-2"><strong>{item.name}</strong>{badge(item.currentness)}<span className="text-xs text-slate-500">{item.role} · {item.buyingRole.replace(/_/g, ' ')}</span></div><p className="mt-2 text-sm text-slate-600">{item.rationale}</p>{evidenceFor(item.claimId)}</article>)}</div> : empty('No sourced current stakeholders found. Contact details remain unknown unless a source provides them.'))}
      {tab === 'signals' && (intelligence.signals.length ? <div className="space-y-3">{intelligence.signals.map(item => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center gap-2"><strong className="capitalize">{item.signalType.replace(/_/g, ' ')}</strong>{badge(item.strength)}{item.eventDate && <span className="text-xs text-slate-500">{item.eventDate}</span>}</div><p className="mt-2 text-sm text-slate-600">{item.interpretation}</p>{evidenceFor(item.claimId)}</article>)}</div> : empty('No discrete, evidence-backed buying signals found.'))}
      {tab === 'gaps' && (intelligence.gaps.length ? <div className="space-y-3">{intelligence.gaps.map(item => <article key={item.id} className="rounded-xl border border-amber-200 bg-amber-50/40 p-4"><div className="flex flex-wrap items-center gap-2"><strong>Discovery hypothesis</strong>{badge(item.certainty)}</div><p className="mt-2 text-sm text-slate-700">{item.statement}</p><p className="mt-2 text-sm text-slate-600">Why ask: {item.rationale}</p>{evidenceFor(item.claimId)}</article>)}</div> : empty('No evidence-backed gap hypotheses. Missing public information is not treated as a gap.'))}
      {tab === 'sources' && (evidence?.sources.length ? <ul className="space-y-2">{evidence.sources.map(source => <li key={source.id} className="rounded-xl border border-slate-200 p-3 text-sm"><a href={source.url} target="_blank" rel="noopener noreferrer" className="font-bold text-teal-700 underline">{source.title || source.url}</a><p className="mt-1 text-xs text-slate-500">{source.sourceType} · Retrieved {new Date(source.retrievedAt).toLocaleString()}{source.publishedAt ? ` · Published ${new Date(source.publishedAt).toLocaleDateString()}` : ''}</p></li>)}</ul> : empty('No source list available for this research run.'))}
    </div>
  </section>;
};
